[Work in progress] add person resource information
openmrs/openmrs-contrib-rest-api-docs pull request #15
Opened 2019-10-31 01:57 UTC by batbrain7

add person resource doc and refactor the patientIdentifierType file inside the patients folder

2019-11-06 14:43 UTC, Akayeshmantha commented
@batbrain7  can u squash the commis please ?

2019-11-06 14:55 UTC, batbrain7 commented
> @batbrain7 can u squash the commis please ?

@Akayeshmantha the PR is quite big and has multiple steps, I did not squash the commits intentionally so that anyone can traceback to the commit easily to know the change that was made whenever required

2019-11-10 05:52 UTC, bmamlin requested changes

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +     Fetch all non-retired persons that match the search query parameter. Returns a 200 OK status with the Person response.
Persons are [voided](https://docs.openmrs.org/datamodel/openmrs-refapp-data-model-1.9.html#%5Eperson%24.void), not retired.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *q* | *query_string* | *Any string in general against which the results should be filtered out*
The "type" is "String". The description should state what will be searched. Presumably, it would search names. But does it also search within addresses or person attributes? Is the search case insensitive?

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    GET /person/?q=query_string
It would be better to give a realistic example. Please don't put a slash (`/`) after the resource.

`GET /person?q=john`

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +* To create a person you need to specify the below properties in the request. If you are not logged in to perform this action, a `401 Unauthorized` status is returned.
`401 Unauthorized` is returned if the request is not authenticated or if the authenticated user does not have appropriate permissions.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *gender* | String | A value to indicate the gender, for eg: "M" for male
The patient's gender ("M" for male, "F" for female, or "U" for unknown)

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *age* | Integer | Integer value to denote the age
The estimated age in years. Used when birthdate is unknown.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *birthDateEstimated* | Boolean | A true/false value to denote whether the birthdate is a correct estimate or not
True if the birthdate is estimated; false if birthdate is accurate.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *dead* | Boolean | A true/false value to denote whether a person is dead or not
True if the patient is dead.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *causeOfDeath* | String | Reason for the death of the person
`causeOfDeath` type is _not_ `String`, it's `Concept UUID`

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *deathdateEstimated* | Boolean | A true/false value to denote whether the deathDate is a correct estimate or not
`true` if deathDate is estimate; `false` if deathDate is accurate

Please move this attribute up beneath `causeOfDeath`

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +    *birthTime* | String | The time of birth of the person
Please move this after birthDateEstimated

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +* Update a target person with given UUID, this method only modifies properties in the request. Returns a `404 Not Found`
Update a person. This method only modifies properties specified in the request. Returns a `404 Not found`

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +status if person not exists. If user not logged in to perform this action, a `401 Unauthorized` status returned.
"If user not logged in" doesn't really apply in a REST API, since there isn't a "log in" step in a stateless API. Instead, credentials are sent with every request. I'd suggest rephrasing these lines with something like:

> If not authenticated or authenticated user does not have sufficient privileges, `401 Unauthorized` status returned.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +        "birthdate": "1997-01-13",
In general, `age` _or_ `birthdate` would be supplied, but not both. When the birthdate is provided, there's no need to provide `age` (it's implied). When the birthdate is unknown, then the person's `age` can be provided as a form of approximation (i.e., when someone says "I was born on 13 January, 1997" you can submit their birthdate; when someone says "I don't know my birthdate, but I know I'm 22 years old" you can submit their age).

For this example, I'd suggest omitting the `age` line.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +* Delete or Void a target person by its UUID. Returns a `404 Not Found` status if person not exists.If user
You don't need to say "by its UUID", since this is implied/expected in a REST API. It similar to saying "You can call this person by their phone number" where the "by their phone number" is unnecessary.

Please include a space after a period ending a sentence (before "If" in this line).

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +### List person name subresource
`### List person names`

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +17. [Delete person attribute subresources](#delete-person-name-subresource)
Please remove "subresources" from these titles. It would read better as:
* List person names
* Add person names
* Update person names
* Delete person name
* List person addresses
* etc.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +* List all the person name subresource corresponding to a `target_person_uuid`. Returns a `404 Not Found` status if person name not exists. If user not logged in to perform this action, a `401 unauth
```
List all names for the given person. Returns `404 Not Found` status if the person does not exist. 
If not authenticated or authenticated user does not have sufficient privileges, a `401 Unauthorized` 
status is returned.
```

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*givenname* | `String` | name of the person
`givenName` (the 2nd "N" is capitalized)

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*middlename* | `String` | middle name of the person
`middleName` (the "N" is capitalized)

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*preferred* | `Boolean` | preferred/not preferred name
`true` if this is the person's preferred name. When a person has only one name, it should be marked as preferred; when a person has multiple names, only one name can be preferred.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*givenname* | `String` | name of the person
`givenName`

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*middlename* | `String` | middle name of the person
`middleName`

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*preferred* | `Boolean` | preferred/not preferred address
`true` if this is the person's preferred address. If a person has multiple addresses, only one can be preferred.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*startDate* | `String` | start date of living by the person
date when the person began living at this address

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*endDate* | `String` | end date of living by the person
date when the person stopped living at this address

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*lattitude* | `String` | lattitude of the location of the person
lattitude of the address

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*longitude* | `String` | longitude of the location of the person
longitude of the address

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*longitude* | `String` | longitude of the location of the person
same feedback as above (for creating an address)

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +* Delete or retire a target address sub resource by its UUID.Returns a `404 Not Found` status if attribute not exists.
Addresses are [voided](https://docs.openmrs.org/datamodel/openmrs-refapp-data-model-1.9.html#person_address.void), not retired.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +* List all the person attribute subresource by it's `UUID` and corresponding to a `target_person_uuid`. Returns a `404 Not Found` status if person attribute not exists. If user not logged in to perfo
* List all person attributes for a given person. Returns a `404 Not Found` if the person doesn't exist. If not authenticated or the authenticated user does not have sufficient privileges, a `401 Unauthorized` status is returned.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*hydratedObject* | `UUID` | UUID of the hydrated person attribute object
I'm not sure what this "hydrated person attribute" is. Is it not sufficient to simply specify the person attribute type and the value for it?

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +*hydratedObject* | `UUID` | UUID of the hydrated person attribute object
Again, not sure what this `hydratedObject` is or how to find a UUID for one.

2019-11-10 05:52 UTC, bmamlin commented on Person/persons.md
> +* Delete or retire a target attribute sub resource by its UUID. Returns a `404 Not Found` status if attribute not exists.
Person attributes are [voided](https://docs.openmrs.org/datamodel/openmrs-refapp-data-model-1.9.html#person_attribute.void), not retired.

2019-11-11 05:23 UTC, merged