OCRAD-20 :- add concept map type document.
openmrs/openmrs-contrib-rest-api-docs pull request #28
Opened 2019-11-10 19:49 UTC by Akayeshmantha

2019-11-13 06:02 UTC, bmamlin requested changes

2019-11-13 06:02 UTC, bmamlin commented on Concepts/concept_map_type.md
> +4. [Delete a concept_map type](#delete-a-concept-map-type)
* List concept mapping types
* Create a concept mapping type
* Update a concept mapping type
* Delete a concept mapping type

2019-11-13 06:02 UTC, bmamlin commented on Concepts/concept_map_type.md
> +    *q* | `Search Query` | Display Name of concept map Type.
Type is "String"

Description is "Full or partial name search term. Search is case insensitive."

2019-11-13 06:02 UTC, bmamlin commented on Concepts/concept_map_type.md
> +    GET /conceptmaptype?q="Search Query"
Space is not allowed in a URL. Perhaps something like:

`GET /conceptmaptype?q=same`

2019-11-13 06:02 UTC, bmamlin commented on Concepts/concept_map_type.md
> +    *description* | `String` | Description
"A brief description of the concept mapping type"

2019-11-13 06:02 UTC, bmamlin commented on Concepts/concept_map_type.md
> +    *name* | `String` | Name of the concept attribute type (Required)
I think you mean "concept mapping type" (not "concept attribute type")

2019-11-18 19:50 UTC, Akayeshmantha commented
@bmamlin  did the review fixes here

2019-11-27 21:14 UTC, merged