OCRAD-21 :- add concept class type document.
openmrs/openmrs-contrib-rest-api-docs pull request #29
Opened 2019-11-10 20:06 UTC by Akayeshmantha

2019-11-13 06:09 UTC, bmamlin requested changes

2019-11-13 06:09 UTC, bmamlin commented on Concepts/concepts_class.md
> +# Concept Class Type
`# Concept Class`

(remove "Type")

2019-11-13 06:09 UTC, bmamlin commented on Concepts/concepts_class.md
> +4. [Delete a concept_class type](#delete-a-concept-class-type)
Remove the term "type(s)"

* List concept classes
* Create a concept class
* Update a concept class
* Delete a concept class

2019-11-13 06:09 UTC, bmamlin commented on Concepts/concepts_class.md
> +    GET /conceptclass?q="Search Query"
Did this work for you? In my testing, using the `q` parameter doesn't work (I get an empty list back if `q` is set)

2019-11-18 19:57 UTC, Akayeshmantha commented
@bmamlin  done the changes here

2019-11-27 21:15 UTC, merged