OCRAD-23 :- add concept reference term type document.
openmrs/openmrs-contrib-rest-api-docs pull request #30
Opened 2019-11-10 20:38 UTC by Akayeshmantha

2019-11-13 06:24 UTC, bmamlin requested changes

2019-11-13 06:24 UTC, bmamlin commented on Concepts/concept_reference_term_type.md
> +# Concepts Reference Term Type
`# Concept Reference Term`

Singular "Concept" and remove the word "Type"

2019-11-13 06:24 UTC, bmamlin commented on Concepts/concept_reference_term_type.md
> +4.  [Delete a concept reference term type](#delete-a-concept-reference-term-type)
Remove the term "type(s)"

2019-11-13 06:24 UTC, bmamlin commented on Concepts/concept_reference_term_type.md
> +concept dictionary terms are used to refer to concepts by concept_id or name of a concept in the concept dictionary (ie. CIEL, PIH, AMPATH, etc.).
```
* Concept reference terms represent terms within external vocabularies (typically standardized 
terminologies like SNOMED, ICD, LOINC, etc.). OpenMRS concept can be mapped to these 
reference terms through [concept mappings](concept_mapping.md).
```

2019-11-13 06:24 UTC, bmamlin commented on Concepts/concept_reference_term_type.md
> +    *q* | `Search Query` | Display Name of oncepts reference term type object
Does this work for you? In my testing, I was unable to find any concept reference terms using the `q` parameter.

2019-11-18 20:25 UTC, Akayeshmantha commented
@bmamlin did the changes.

2019-11-27 21:16 UTC, merged